//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Debilidad { get; set; }
        public string Evolucion { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public int Numero { get; set; }
    }
}
