//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Id { get; set; }
        public int RolId { get; set; }
        public string Usuario1 { get; set; }
        public byte[] Contraseña { get; set; }
        public string Nombre { get; set; }
    
        public virtual Roles Role { get; set; }
    }
}
